### ISSUE TITLE
DOC: needs docs

### ISSUE THREAD

**Issue by CJ-Wright** [diffpy/diffpy.pdfmorph#1]
We need some docs:
- [ ] change docs over to numpy
- [x] setup sphinx
- [x] setup doctr
- [x] setup description

**Comment by RomanMatthew** [comment]
I'll start working on this soon! What do you think would be the closest thing that I could model it after?

**Comment by CJ-Wright** [comment]
the bluesky docs aren't bad: https://github.com/bluesky/bluesky

**Comment by RomanMatthew** [comment]
@sbillinge @CJ-Wright @cfarrow @chiahaoliu @pavoljuhas 

Hello all, 

I'll use this issue to ask some content-related stuff during the doc development. Some of the blanks I'll need help filling in will be evident by a lack of detail/words, but I want to be proactive. Modeling off of the [diffpy.structure](https://diffpystructure.readthedocs.io/en/stable/) docs, my first question is whether or not you guys wanted to put anything in the "Acknowledgements" section of the front page. Let me know! I'll be rolling out more questions as development continues

**Comment by sbillinge** [comment]
nice job @romanmatthew, this is very much appreciated.   We will respond as
best as we can to your questions.
