### ISSUE TITLE
make novice-friendly flow through pdfmorph repo

### ISSUE THREAD

**Issue by RomanMatthew** [diffpy/diffpy.pdfmorph#17]

**Comment by RomanMatthew** [comment]
- README.txt restructure to look more like that from pdfgui
- Context in /requirements/ files
- /news/ seems like it might be a little trivial (changes made seemingly outweigh the changes reported), but I don't really know this context
- Unclear how to use pdfmorph, but this would probably come before publishing

**Comment by sbillinge** [comment]
``news`` is a special directory we use for releasing code.  Each feature or bugfix we do in each PR, we add one or a few news-items.  When the code is released it builds the changelog from the news items.  This is not user-facing, not  part of the user documenentation.

**Comment by sbillinge** [comment]
This is well handled in the latest version.
