### ISSUE TITLE
fix namespace package handling

### ISSUE THREAD

**Issue by RomanMatthew** [diffpy/diffpy.pdfmorph#25]
easy_install and pip have conflicting way of handling namespaced packages (diffpy functions as a namespace only and is not a real package) and a mixed installation then may not work:

$ conda create -n xx36 -c diffpy diffpy.utils
$ conda activate xx36
$ python -c 'import diffpy.utils'    # OK
$ pip install https://github.com/diffpy/diffpy.pdfmorph/archive/master.tar.gz
$ python -c 'import diffpy.utils'    # FAILS
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'diffpy.utils'
This actually happens because of an outdated definition of namespace package in diffpy/init.py which is specific to setuptools (easy_install) and does not work well with pip. Other diffpy packages have that code updated, e.g., diffpy.structure/src/diffpy/init.py, and then it seems to work with both easy_install and pip.

fix namespace package handling in diffpy/__init__.py as in diffpy.structure and
check if mixed easy_install, pip installation of several diffpy packages works OK
and if it does, update README to suggest pip as the installation tool

**Comment by sbillinge** [comment]
I am not sure either.  It is well documented by Roman and may therefore have been fixed if it works.  But the final check I would do if I took it on would be to look and see what I see in `diffpy/init.py` in `diffpy.utils` and compare it with the same file in `diffpy.structure`.   Also to look back through the commit log to see if a fix was merged at some point in the past.   I will take a look when I get a chance, but this would be my feedback.
