### ISSUE TITLE
MANT: change morph data naming

### ISSUE THREAD

**Issue by chiahaoliu** [diffpy/diffpy.pdfmorph#37]
Current proposal:

`objective -> morphed` : data will be manipulated
`reference -> target`: data will stay unchanged.

The `obj-ref` language propagates across the repo (like `xref, yobj` etc), but the convention is rather clear and self-consistent as we always see `xref, yref` remain unchanged in the code.
 
The first order fix could be changing the language in `pdfmorph` function and app since they are user facing.

cc: @sbillinge @pavoljuhas

**Comment by pavoljuhas** [comment]
I think we still need both "objective" and "morphed" names.  "objective" is the input PDF to be morphed and after transformations becomes "morphed" data.

**Comment by sbillinge** [comment]
I want to remove ambiguity which is why I want to move away from
objective-reference names altogether.  For me it is a wild guess which is
the changed and which the unchanged with the latter.  I am not so concerned
about pre post morphing but we could use pre-morph post-morph it sthg if it
makes sense.

**Comment by chloeann95** [comment]
I believe this gets closed by #46 unless you want me to go through the code and change the code names used throughout as well. Indicating which file is morphed could be done better in the help menu or even in the readout where it gives morphing parameters. Could say something like "X was morphed with" prior to giving the morphing parameters to better remove ambiguity or having to search in the help menu.

**Comment by sbillinge** [comment]
No, this is not closed by #46.  I put comments on that PR to that effect, but I can merge that PR and we can fix this on this PR.  Tasks would be:

1. Look in documentation and change everywhere `objective -> morph`  (data will be manipulated) and `reference -> target) (data will stay unchanged).
2. Look everywhere in code comments and make the same mapping
3. Add words to the docs and the README.md that explains the meaning of the words
4. This is more tricky as getting it wrong will break the code, but change all variables in the code that link to the old naming scheme to reflect the new, so `xobjin` -> `x_morph_in` or sthg.  The underscores or not depend on making the code as readable and clear as possible.

Doing global searches for the terms in PyCharm and using its "refactor" capabilities should help, but double-check any global copy-replace activities.  Being a bit hands-on will help
