### ISSUE TITLE
whitespace errors

### ISSUE THREAD

**Issue by pavoljuhas** [diffpy/diffpy.pdfmorph#42]
@RomanMatthew  - can you please fix whitespace problems reported by

```sh
$ git diff --check df96a1599

AUTHORS.rst:5: trailing whitespace.
+Chia-Hao (Timothy) Liu, Timur Davis, S. Matthew Román, Simon J.L. 
AUTHORS.rst:10: trailing whitespace.
+For a list of contributors, visit 
CHANGELOG.rst:13: new blank line at EOF.
README.rst:12: trailing whitespace.
+PDFmorph is a Python software package designed to increase the insight 
README.rst:13: trailing whitespace.
+researchers can obtain from measured atomic pair distribution functions 
...
```

all - please use git pre-commit check to avoid whitespace errors:

```sh
$ cd .git/hooks
$ cp pre-commit.sample pre-commit
```

**Comment by RomanMatthew** [comment]
Which branch is this in?

**Comment by pavoljuhas** [comment]
`master`.  Note `git diff --check` shows one spurious error for `leftover conflict marker`, but otherwise all other issues should be corrected.

**Comment by chloeann95** [comment]
I'm fairly certain this is fixed, I can't find any trailing whitespaces in the two files shown.

**Comment by sbillinge** [comment]
To be certain perhaps 
1) look at the git log and find the commit `df96a1599`
2) look for a commit after that that claims to fix the problem
3) run the `git diff --check <commit hash>` on that commit and make sure that the errors are gone
4) to be super-safe, find the most recent commit and run the diff check on that.

**Comment by chloeann95** [comment]
It looks like the only thing not fixed is the conflict marker. From the looks of what I can find online the "=======" line under authors is throwing the "leftover conflict marker" error but shouldn't affect functionality.

**Comment by chloeann95** [comment]
It's to center the Authors title in the .rst
