### ISSUE TITLE
PDFmorph outputs the values of the parameters that it used

### ISSUE THREAD

**Issue by sbillinge** [diffpy/diffpy.pdfmorph#44]
I may just not know how to use the software, but is there no way to output the values it used for the morphing?  Add values to the output.

**Comment by sbillinge** [comment]
OK, update, if you specify parameters as a command line switch it will return the values.  So this issue would be to specify them whether they were specified or not.

**Comment by chloeann95** [comment]
PDFmorph currently outputs the parameters that it fits on the command line. Do you want it to also output the inputs? Or do you want them to output this data somewhere other than the command line.

**Comment by chloeann95** [comment]
If you don't specify the parameters it doesn't do anything with them so they'd be 1, 0, 0 for scale, stretch, smear respectively

**Comment by sbillinge** [comment]
is there a question somewhere here?  If yes, I would say that what we want is that the starting and ending parameters are recorded.  I would say the UC that this is serving is:

1. User morphs a dataset onto another dataset
2. PDFmorph does the morphing and reports back results on the screen and optionally to an output file
3. User wants to know if the parameters changed by a lot or just a little
4. User looks at the output and gets this information

**Comment by chloeann95** [comment]
alright
