### ISSUE TITLE
allow people to save the morphed PDF file as a new G(r) file

### ISSUE THREAD

**Issue by chloeann95** [diffpy/diffpy.pdfmorph#47]

**Comment by sbillinge** [comment]
Please check,  I think this is one of the command line options,  so already
present.   If that functionality is ok we can close this issue, but if you
think some different functionality is needed let's discuss it here

**Comment by chloeann95** [comment]
> 

There's nothing in the pdfmorph -h help menu, I know we couldn't find anything when we met last week. If the functionality is there this could be changed to including it in the help menu but I can't find it.

**Comment by sbillinge** [comment]
OK,  we can fix it then,  but double check.  I thought I saw it.

**Comment by chloeann95** [comment]
I was wrong before because I was looking for the wrong thing, this is an option using the -s FILE command so I believe this can be closed. I do want to double check the documentation as to which file's morph it changes, some of the stuff just says "FILE1" but I want to make sure if anything was linked to the "reference" and "objective" name case so it's properly documented.

**Comment by sbillinge** [comment]
I will close this when the docs have been checked.
