### ISSUE TITLE
make GH action that publishes documentation automatically on release

### ISSUE THREAD

**Issue by sbillinge** [diffpy/diffpy.pdfmorph#52]

**Comment by Sparks29032** [comment]
This can be done with a [GitHub workflow](https://docs.github.com/en/actions/quickstart). For reference, [here](https://github.com/diffpy/diffpy.utils/blob/main/.github/workflows/docs.yml) is a GitHub workflow from `diffpy.utils` that automatically builds and publishes documentation on release.

Our implementation for `pdfmorph` may be a bit different as we may want to host `pdfmorph` docs on the [`diffpy` website](https://github.com/diffpy/diffpy.github.io).
