### ISSUE TITLE
pytest for all the tests

### ISSUE THREAD

**Issue by CJ-Wright** [diffpy/diffpy.pdfmorph#6]

**Comment by pavoljuhas** [comment]
pytest sounds good.  I'd also suggest to include the tests directory within Python package as a `diffpy.pdfmorph.tests` module and add there the `.../tests/run.py` launcher from some other diffpy project.

It would make it easier to test an installed pdfmorph and would let us test all diffpy packages in a uniform way with `python -m diffpy.SOMETHING.tests.run`.

**Comment by CJ-Wright** [comment]
Sure PRs are welcome (once the initial PR is in).
