### ISSUE TITLE
Finalize morphshape and morphishape testing

### ISSUE THREAD

**Issue by Sparks29032** [diffpy/diffpy.pdfmorph#79]
Issue can be resolved after 0.0.1 release.
- Need to determine behavior at `psize` for `MorphISpheroid`. Do we (1) set to zero or (2) divide by characteristic function. Current test data has set to zero, but `_spheroidalCF` does not set the characteristic function to zero at the boundary.
- Add prolate spheroid test data.

**Comment by sbillinge** [comment]
closed by #80
