### ISSUE TITLE
rebase on a full import from subversion

### ISSUE THREAD

**Issue by pavoljuhas** [diffpy/diffpy.pdfmorph#8]
I have added new branch `master-svn-import` with a complete import of project history from subversion.    The only difference from the current master 243661ae7cbda0e389ff177baa2bce73dfcf46f6 is in expansion of svn keywords.

Can we reset master to 6b1816f9b1e505a0055baa99dd5622cf0daaca2e and rebase all PRs on that commit?

**Comment by pavoljuhas** [comment]
@chiahaoliu, @CJ-Wright - can we resolve this issue before opening any new PRs?

I suggest to do this change and preserve the past history of the code.
I find it useful to be able to do `git blame` or `git log -p` to understand when and
why some piece of the code come along.

**Comment by chiahaoliu** [comment]
@pavoljuhas sure. I am on it.

Sorry I didn't see this issue by the moment it was created.

**Comment by chiahaoliu** [comment]
It seems I can't issue a PR from ``master-svn-import`` into ``master`` because of largely different commit history, tho the body of  code is not too different.

Would you guys mind me doing ``reset`` and ``push -f``?  Or maybe there is a better way?

@pavoljuhas @CJ-Wright

**Comment by pavoljuhas** [comment]
Yes, `reset` and `push --force-with-lease` is the way to go; that is what I was suggesting.

I just want to be sure we are all on the same page about doing that.

**Comment by CJ-Wright** [comment]
That's fine

**Comment by pavoljuhas** [comment]
Done.  Please, rebase your PR branches onto the new master 6b1816f9b1e505a0055baa99dd5622cf0daaca2e, i.e., do
```sh
git checkout your-pr-branch
git rebase --onto 6b1816f9b 243661ae7
```


It seems resetting the master closed all PRs, but pushing a rebased branch should open them back.
